const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const { Finance } = require('../models');

function calcRAD(marche_ds, total_depenses, travaux_supplementaires) {
  return (marche_ds || 0) - (total_depenses || 0) + (travaux_supplementaires || 0);
  }

  router.get('/project/:projectId', auth, async (req, res) => {
    try {
        const finances = await Finance.find({ project: req.params.projectId })
              .populate('createdBy', 'name').sort({ createdAt: -1 });
                  res.json(finances);
                    } catch (error) { res.status(500).json({ error: error.message }); }
                    });

                    router.get('/:id', auth, async (req, res) => {
                      try {
                          const finance = await Finance.findById(req.params.id).populate('createdBy', 'name');
                              if (!finance) return res.status(404).json({ error: 'Not found' });
                                  res.json(finance);
                                    } catch (error) { res.status(500).json({ error: error.message }); }
                                    });

                                    router.post('/', auth, async (req, res) => {
                                      try {
                                          const data = { ...req.body, createdBy: req.userId };
                                              data.rad = calcRAD(data.marche_ds, data.total_depenses, data.travaux_supplementaires);
                                                  const finance = new Finance(data);
                                                      await finance.save();
                                                          await finance.populate('createdBy', 'name');
                                                              res.status(201).json(finance);
                                                                } catch (error) { res.status(500).json({ error: error.message }); }
                                                                });

                                                                router.put('/:id', auth, async (req, res) => {
                                                                  try {
                                                                      const data = { ...req.body, updatedAt: new Date() };
                                                                          data.rad = calcRAD(data.marche_ds, data.total_depenses, data.travaux_supplementaires);
                                                                              const finance = await Finance.findByIdAndUpdate(req.params.id, data, { new: true })
                                                                                    .populate('createdBy', 'name');
                                                                                        if (!finance) return res.status(404).json({ error: 'Not found' });
                                                                                            res.json(finance);
                                                                                              } catch (error) { res.status(500).json({ error: error.message }); }
                                                                                              });

                                                                                              router.delete('/:id', auth, async (req, res) => {
                                                                                                try {
                                                                                                    const finance = await Finance.findByIdAndDelete(req.params.id);
                                                                                                        if (!finance) return res.status(404).json({ error: 'Not found' });
                                                                                                            res.json({ message: 'Deleted' });
                                                                                                              } catch (error) { res.status(500).json({ error: error.message }); }
                                                                                                              });

                                                                                                              // Export Excel
                                                                                                              router.get('/project/:projectId/export/excel', auth, async (req, res) => {
                                                                                                                try {
                                                                                                                    const ExcelJS = require('exceljs');
                                                                                                                        const finances = await Finance.find({ project: req.params.projectId })
                                                                                                                              .populate('createdBy', 'name').sort({ createdAt: -1 });
                                                                                                                                  const workbook = new ExcelJS.Workbook();
                                                                                                                                      const sheet = workbook.addWorksheet('Finances');
                                                                                                                                          sheet.columns = [
                                                                                                                                                { header: 'Periode', key: 'periode', width: 14 },
                                                                                                                                                      { header: 'Montant Marche (EUR)', key: 'montant_marche', width: 22 },
                                                                                                                                                            { header: 'Marche DS (EUR)', key: 'marche_ds', width: 18 },
                                                                                                                                                                  { header: '% Marche/DS', key: 'pct_mds', width: 14 },
                                                                                                                                                                        { header: 'Total Depenses (EUR)', key: 'total_depenses', width: 22 },
                                                                                                                                                                              { header: 'Trav. Supp (EUR)', key: 'travaux_supplementaires', width: 18 },
                                                                                                                                                                                    { header: 'RAD (EUR)', key: 'rad', width: 14 },
                                                                                                                                                                                          { header: 'Fact. Mois (EUR)', key: 'facturation_mois', width: 18 },
                                                                                                                                                                                                { header: 'Dep. Mois (EUR)', key: 'depenses_mois', width: 16 },
                                                                                                                                                                                                      { header: 'Resultat Mois (EUR)', key: 'resultat_mois', width: 20 },
                                                                                                                                                                                                            { header: '% Resultat', key: 'pct_res', width: 12 },
                                                                                                                                                                                                                  { header: 'Notes', key: 'notes', width: 30 },
                                                                                                                                                                                                                        { header: 'Cree par', key: 'createdBy', width: 15 },
                                                                                                                                                                                                                            ];
                                                                                                                                                                                                                                const hr = sheet.getRow(1);
                                                                                                                                                                                                                                    hr.font = { bold: true, color: { argb: 'FFFFFFFF' } };
                                                                                                                                                                                                                                        hr.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1B4F72' } };
                                                                                                                                                                                                                                            finances.forEach((f, idx) => {
                                                                                                                                                                                                                                                  const pct_mds = f.montant_marche ? ((f.marche_ds / f.montant_marche) * 100).toFixed(1) + '%' : '-';
                                                                                                                                                                                                                                                        const resultat_mois = (f.facturation_mois || 0) - (f.depenses_mois || 0);
                                                                                                                                                                                                                                                              const pct_res = f.facturation_mois ? ((resultat_mois / f.facturation_mois) * 100).toFixed(1) + '%' : '-';
                                                                                                                                                                                                                                                                    const row = sheet.addRow({
                                                                                                                                                                                                                                                                            periode: f.periode || '-', montant_marche: f.montant_marche || 0,
                                                                                                                                                                                                                                                                                    marche_ds: f.marche_ds || 0, pct_mds,
                                                                                                                                                                                                                                                                                            total_depenses: f.total_depenses || 0,
                                                                                                                                                                                                                                                                                                    travaux_supplementaires: f.travaux_supplementaires || 0,
                                                                                                                                                                                                                                                                                                            rad: f.rad || 0, facturation_mois: f.facturation_mois || 0,
                                                                                                                                                                                                                                                                                                                    depenses_mois: f.depenses_mois || 0, resultat_mois, pct_res,
                                                                                                                                                                                                                                                                                                                            notes: f.notes || '', createdBy: f.createdBy ? f.createdBy.name : '-',
                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                        if (idx % 2 === 0) row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEBF5FB' } };
                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
                                                                                                                                                                                                                                                                                                                                                    res.setHeader('Content-Disposition', 'attachment; filename=finances.xlsx');
                                                                                                                                                                                                                                                                                                                                                        await workbook.xlsx.write(res);
                                                                                                                                                                                                                                                                                                                                                            res.end();
                                                                                                                                                                                                                                                                                                                                                              } catch (error) { res.status(500).json({ error: error.message }); }
                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                              // Export PDF
                                                                                                                                                                                                                                                                                                                                                              router.get('/project/:projectId/export/pdf', auth, async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                    const PDFDocument = require('pdfkit');
                                                                                                                                                                                                                                                                                                                                                                        const finances = await Finance.find({ project: req.params.projectId })
                                                                                                                                                                                                                                                                                                                                                                              .populate('createdBy', 'name').sort({ createdAt: -1 });
                                                                                                                                                                                                                                                                                                                                                                                  const doc = new PDFDocument({ margin: 30, size: 'A4', layout: 'landscape' });
                                                                                                                                                                                                                                                                                                                                                                                      res.setHeader('Content-Type', 'application/pdf');
                                                                                                                                                                                                                                                                                                                                                                                          res.setHeader('Content-Disposition', 'attachment; filename=finances.pdf');
                                                                                                                                                                                                                                                                                                                                                                                              doc.pipe(res);
                                                                                                                                                                                                                                                                                                                                                                                                  doc.fontSize(16).fillColor('#1B4F72').text('Rapport Finances', { align: 'center' });
                                                                                                                                                                                                                                                                                                                                                                                                      doc.fontSize(9).fillColor('#555').text('Exporte le ' + new Date().toLocaleDateString('fr-FR'), { align: 'center' });
                                                                                                                                                                                                                                                                                                                                                                                                          doc.moveDown(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                              const headers = ['Periode', 'Marche', 'DS', '%M/DS', 'Depenses', 'T.Supp', 'RAD', 'Fact.Mois', 'Dep.Mois', 'Resultat', '%'];
                                                                                                                                                                                                                                                                                                                                                                                                                  const colW = [52, 62, 62, 40, 62, 52, 52, 62, 62, 62, 38];
                                                                                                                                                                                                                                                                                                                                                                                                                      const startX = 20;
                                                                                                                                                                                                                                                                                                                                                                                                                          let y = doc.y;
                                                                                                                                                                                                                                                                                                                                                                                                                              let x = startX;
                                                                                                                                                                                                                                                                                                                                                                                                                                  headers.forEach((h, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        doc.rect(x, y, colW[i], 16).fill('#1B4F72');
                                                                                                                                                                                                                                                                                                                                                                                                                                              doc.fillColor('white').fontSize(7).text(h, x + 2, y + 4, { width: colW[i] - 4, lineBreak: false });
                                                                                                                                                                                                                                                                                                                                                                                                                                                    x += colW[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                            y += 16;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                finances.forEach((f, idx) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const pct_mds = f.montant_marche ? ((f.marche_ds / f.montant_marche) * 100).toFixed(1) + '%' : '-';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const rm = (f.facturation_mois || 0) - (f.depenses_mois || 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const pct_r = f.facturation_mois ? ((rm / f.facturation_mois) * 100).toFixed(1) + '%' : '-';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const vals = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f.periode || '-',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (f.montant_marche || 0).toLocaleString('fr-FR'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (f.marche_ds || 0).toLocaleString('fr-FR'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pct_mds,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (f.total_depenses || 0).toLocaleString('fr-FR'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (f.travaux_supplementaires || 0).toLocaleString('fr-FR'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (f.rad || 0).toLocaleString('fr-FR'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (f.facturation_mois || 0).toLocaleString('fr-FR'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (f.depenses_mois || 0).toLocaleString('fr-FR'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rm.toLocaleString('fr-FR'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pct_r,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const bg = idx % 2 === 0 ? '#EBF5FB' : '#FFFFFF';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  x = startX;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        vals.forEach((v, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                doc.rect(x, y, colW[i], 13).fill(bg);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        doc.fillColor('#333').fontSize(7).text(String(v), x + 2, y + 3, { width: colW[i] - 4, lineBreak: false });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x += colW[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            y += 13;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (y > 550) { doc.addPage({ layout: 'landscape' }); y = 30; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc.end();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) { res.status(500).json({ error: error.message }); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            module.exports = router;